events {
    worker_connections 1024;
}

http {
    # Tentukan upstream untuk master-api
    upstream api_backend {
        # 'master-api' adalah nama service di docker-compose
        server master-api:4000;
    }

    server {
        listen 80;

        # (Opsional) Ganti dengan domain Anda jika ada
        server_name 136.113.4.138;

        location / {
            proxy_pass http://api_backend;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;

            # Teruskan IP asli klien ke aplikasi Node.js
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
